### ISSUE TITLE
Classy_enum with actual enum fields?

### ISSUE THREAD

**Issue by PeteMichaud** [beerlington/classy_enum#55]
Hey man, long time user of classy_enum, awesome work!

I'm working in rails 4.2 and pg, and I have a field that I want to just call an enum right at the database level since such a thing is possible now. Could you maybe write a quite how-to in the readme about how to use that instead of a string field?

**Comment by beerlington** [comment]
Hi Pete, it's great to hear from people who like the gem!

I *think* what you're talking about is possible without needing to do anything special. I've never actually done it in a production app, but a couple years ago someone opened an issue and I explored it a bit using MySQL. Some people have confirmed that it works with PostgreSQL too. https://github.com/beerlington/classy_enum/issues/12

Let me know if you run into any issues and I'd be happy to help troubleshoot.
