### ISSUE TITLE
Rails 5.x update

### ISSUE THREAD

**Issue by victor-am** [beerlington/classy_enum#58]
Hello there 😄 

I was wondering if there are any plans on updating the gem to Rails 5.x and Ruby 2.4.x? 🤔 
Or is it compatible already?

Also, what is the status of this gem, it's still being maintained?

I found the concept interesting for state machines and general enums (used in two projects some time ago, one from real life and one pet project) 😆

**Comment by victor-am** [comment]
Ops, nevermind, I saw the contributing guide now with the maintenance info 😞

**Comment by beerlington** [comment]
@victor-am it's not maintained in the sense of adding new features, but would be happy to review any PRs to make it compatible with newer versions of Rails and Ruby. My team and I have moved onto Elixir so I don't use this in new projects.
